services:
  dnsserver:
    build: dnsserver
    #entrypoint: tail -f /dev/null
    hostname: dnsserver
    ports:
      - 10.26.0.32:53:53    #So na rede principal
    volumes:
      - ./dnsserver/named.conf.options:/etc/bind/named.conf.options
      - ./dnsserver/named.conf.local:/etc/bind/named.conf.local
      - ./dnsserver/db.starwars.lan:/etc/bind/db.starwars.lan
      - ./dnsserver/db.25.172:/etc/bind/db.25.172
    networks:
      rededns:
        ipv4_address: 172.25.0.11
  cliente:
    build: cliente
    hostname: cliente1
    networks:
      rededns:
        ipv4_address: 172.25.0.100
    dns: 172.25.0.11
networks:
  rededns:
    ipam:
      config:
        - subnet: 172.25.0.0/16


